#
#

# ------------------------------------------------------------------ 
# paths
# ------------------------------------------------------------------ 

LIBDIR =    ../lib
BINDIR =    ../bin
MANDIR =    ../man


# ------------------------------------------------------------------  
# high level targets
# ------------------------------------------------------------------  

test:V:         fp regression

fp:V:           fixpoint 
                for f in fix-*[0-9][0-9].c--; do ./fixpoint $f; done

regression:V:   regr
                
                for f in error*.c-- ; do
                    g=`basename $f .c--`
                    CMD="../bin/qc-- -check $g.c--"
                    ./regr "$CMD" -x 1 -err $g.stderr || true
                done

%.stderr:       %.c--
                ./regr "../bin/qc-- -check $stem.c--" -r -err $stem.stderr 
                head -v $stem.stderr

scripts:V:      fixpoint regr        

# ------------------------------------------------------------------ 
# Noweb stuff - once this is stable the generic part should go to
# ../config/noweb.mk
# ------------------------------------------------------------------ 

NOWEAVE =       noweave
NOTANGLE =      notangle
CPIF =          cpif
RERUN =         Rerun (LaTeX|to get cross-references right)

LINE =          '# %L "%F"%N'
OCAMLTANGLE =   'for f in $target; do $NOTANGLE -L"$LINE" -R$f $prereq | $CPIF $f; done'
MISCTANGLE  =   'for f in $target; do $NOTANGLE -R$f $prereq | $CPIF $f; done'

HTML =          `echo *.nw       | sed 's/\.nw/.html/g;'`

%.inc:          %.nw
                $NOWEAVE -delay $prereq > $target

%.html:         %.nw
                $NOWEAVE -delay -html -filter l2h $prereq > $target

# ------------------------------------------------------------------  
# sources generated from noweb sources
# ------------------------------------------------------------------  

fixpoint        \
regr:           test.nw
                eval $MISCTANGLE
                chmod +x $target

html:V:         $HTML
