SRC=myList.ml pprint.ml syntax.ml code.ml spec.ml pc.ml token.ml srcmap.ml lex.ml parse.ml norm.ml burg.ml main.ml 
BIN=`echo $SRC | sed 's/\.mli/.cmi/g;s/\.ml /.cmo /g;s/.ml$/.cmo/'`
TEST=test.ml test2.ml

LIBDIR=../lib

<../config/ocaml.mk

LINE =          '# %L "%F"%N'

%.tex: %.nw
	noweave -autodefs ocaml -index $prereq > $target

%.ml: %.nw
	notangle -L"$LINE" -R$target $prereq > $target

%.mli: %.nw
	notangle -L"$LINE" -R$target $prereq > $target

all:V: mlburg

lex.mll: lex.nw
	notangle -R$target $prereq > $target

main.ml: burg.nw
	notangle -L"$LINE" -R$target $prereq > $target

mlburg: $BIN
	ocamlc -o $target $prereq

clean:V:
	rm -f *.cmi *.cmo
	rm -f *~

clobber:V: clean
	rm -f mlburg

bin:V: $BIN

lex.ml: lex.mll
	ocamllex $prereq

test:V: sample.cmo

^(sample|iburg)'\.'ml'$':R: '\1'.mlb mlburg
	mlburg $stem1.mlb > $target

a.out:	test.cmo test2.cmo
	ocamlc -o $target $prereq

test.ml: ss.ml gen.ml
	cat $prereq > $target

gen.ml: sample.mlb mlburg
	mlburg sample.mlb > $target

token.ml: lex.nw
        notangle -L"$LINE" -R$target $prereq > $target

<DEPEND

depend:V: DEPEND
DEPEND: $SRC 
	ocamldep *.ml *.mli > DEPEND

ss.ml:
	# do nothing
