overflow: overflow.c--  overflow-client.c--  overflow-global.c-- getspan.c invokeclosure.s runtime-internals.o
	qc-- -o overflow -globals overflow.c--  overflow-client.c--  overflow-global.c-- getspan.c invokeclosure.s runtime-internals.o

runtime-internals.o: 
	gcc -c -I../.. runtime-internals.c
