overflow: overflow.c--  overflow-client.c--  overflow-global.c-- getspan.c invokeclosure.s
	qc-- -o overflow -globals  overflow.c--  overflow-client.c--  overflow-global.c-- getspan.c invokeclosure.s
