TOP  = ../../..
<      $TOP/config/config.mk
<      $TOP/config/noweb.mk

NW   = invokeclosure.nw
INC  = ${NW:%.nw=%.inc}

overflow: overflow.c--  overflow-client.c--  overflow-global.c-- getspan.c invokeclosure.s runtime-internals.o
	qc-- peephole.lua -o overflow -globals overflow.c--  overflow-client.c--  overflow-global.c-- getspan.c invokeclosure.s runtime-internals.o

runtime-internals.o: runtime-internals.c
	gcc -g -c -I../.. runtime-internals.c

invokeclosure.s: invokeclosure.nw
	notangle -Rinvokeclosure.s invokeclosure.nw > invokeclosure.s


doc.dvi: doc.tex $INC

