type exp = (allTypes) Syntax.bExp
and allTypes =
  T__reg_or_imm of t__reg_or_imm
| T__address of t__address
| T__regaddr of t__regaddr
| T__t of t__t

and t__reg_or_imm =   Imode of (exp)
                    | Rmode of (exp)
                    
and t__address =
  Generala of (exp * exp)
| Dispa of (exp * exp)
| Absolutea of (exp)
| Indexa of (exp * exp)
| Indirecta of (exp)

and t__regaddr =   Indexr of (exp * exp)
                 | Indirectr of (exp)
                 
and t__t =
  Ldsb of (exp * exp)
| Ldsh of (exp * exp)
| Ldub of (exp * exp)
| Lduh of (exp * exp)
| Ld of (exp * exp)
| Ldstub of (exp * exp)
| Swap_ of (exp * exp)
| Ldd of (exp * exp)
| Ldf of (exp * exp)
| Lddf of (exp * exp)
| Ldc of (exp * exp)
| Lddc of (exp * exp)
| Stb of (exp * exp)
| Sth of (exp * exp)
| St of (exp * exp)
| Std of (exp * exp)
| Stf of (exp * exp)
| Stdf of (exp * exp)
| Stc of (exp * exp)
| Stdc of (exp * exp)
| Ldsba of (exp * exp * exp)
| Ldsha of (exp * exp * exp)
| Lduba of (exp * exp * exp)
| Lduha of (exp * exp * exp)
| Lda of (exp * exp * exp)
| Ldstuba of (exp * exp * exp)
| Swapa of (exp * exp * exp)
| Ldda of (exp * exp * exp)
| Stba of (exp * exp * exp)
| Stha of (exp * exp * exp)
| Sta of (exp * exp * exp)
| Stda of (exp * exp * exp)
| Ldfsr of (exp)
| Ldcsr of (exp)
| Stfsr of (exp)
| Stcsr of (exp)
| Stdfq of (exp)
| Stdcq of (exp)
| Rdy of (exp)
| Rdpsr of (exp)
| Rdwim of (exp)
| Rdtbr of (exp)
| Wry of (exp * exp)
| Wrpsr of (exp * exp)
| Wrwim of (exp * exp)
| Wrtbr of (exp * exp)
| Rdasr of (exp * exp)
| Wrasr of (exp * exp * exp)
| Stbar of unit
| And of (exp * exp * exp)
| Andcc of (exp * exp * exp)
| Andn of (exp * exp * exp)
| Andncc of (exp * exp * exp)
| Or of (exp * exp * exp)
| Orcc of (exp * exp * exp)
| Orn of (exp * exp * exp)
| Orncc of (exp * exp * exp)
| Xor of (exp * exp * exp)
| Xorcc of (exp * exp * exp)
| Xnor of (exp * exp * exp)
| Xnorcc of (exp * exp * exp)
| Sll of (exp * exp * exp)
| Srl of (exp * exp * exp)
| Sra of (exp * exp * exp)
| Add of (exp * exp * exp)
| Addcc of (exp * exp * exp)
| Addx of (exp * exp * exp)
| Addxcc of (exp * exp * exp)
| Taddcc of (exp * exp * exp)
| Taddcctv of (exp * exp * exp)
| Sub of (exp * exp * exp)
| Subcc of (exp * exp * exp)
| Subx of (exp * exp * exp)
| Subxcc of (exp * exp * exp)
| Tsubcc of (exp * exp * exp)
| Tsubcctv of (exp * exp * exp)
| Mulscc of (exp * exp * exp)
| Umul of (exp * exp * exp)
| Smul of (exp * exp * exp)
| Umulcc of (exp * exp * exp)
| Smulcc of (exp * exp * exp)
| Udiv of (exp * exp * exp)
| Sdiv of (exp * exp * exp)
| Udivcc of (exp * exp * exp)
| Sdivcc of (exp * exp * exp)
| Save of (exp * exp * exp)
| Restore of (exp * exp * exp)
| Bn of (exp)
| Bn_a of (exp)
| Be of (exp)
| Be_a of (exp)
| Ble of (exp)
| Ble_a of (exp)
| Bl of (exp)
| Bl_a of (exp)
| Bleu of (exp)
| Bleu_a of (exp)
| Bcs of (exp)
| Bcs_a of (exp)
| Bneg of (exp)
| Bneg_a of (exp)
| Bvs of (exp)
| Bvs_a of (exp)
| Ba of (exp)
| Ba_a of (exp)
| Bne of (exp)
| Bne_a of (exp)
| Bg of (exp)
| Bg_a of (exp)
| Bge of (exp)
| Bge_a of (exp)
| Bgu of (exp)
| Bgu_a of (exp)
| Bcc of (exp)
| Bcc_a of (exp)
| Bpos of (exp)
| Bpos_a of (exp)
| Bvc of (exp)
| Bvc_a of (exp)
| Fbn of (exp)
| Fbn_a of (exp)
| Fbne of (exp)
| Fbne_a of (exp)
| Fblg of (exp)
| Fblg_a of (exp)
| Fbul of (exp)
| Fbul_a of (exp)
| Fbl of (exp)
| Fbl_a of (exp)
| Fbug of (exp)
| Fbug_a of (exp)
| Fbg of (exp)
| Fbg_a of (exp)
| Fbu of (exp)
| Fbu_a of (exp)
| Fba of (exp)
| Fba_a of (exp)
| Fbe of (exp)
| Fbe_a of (exp)
| Fbue of (exp)
| Fbue_a of (exp)
| Fbge of (exp)
| Fbge_a of (exp)
| Fbuge of (exp)
| Fbuge_a of (exp)
| Fble of (exp)
| Fble_a of (exp)
| Fbule of (exp)
| Fbule_a of (exp)
| Fbo of (exp)
| Fbo_a of (exp)
| Cbn of (exp)
| Cbn_a of (exp)
| Cb123 of (exp)
| Cb123_a of (exp)
| Cb12 of (exp)
| Cb12_a of (exp)
| Cb13 of (exp)
| Cb13_a of (exp)
| Cb1 of (exp)
| Cb1_a of (exp)
| Cb23 of (exp)
| Cb23_a of (exp)
| Cb2 of (exp)
| Cb2_a of (exp)
| Cb3 of (exp)
| Cb3_a of (exp)
| Cba of (exp)
| Cba_a of (exp)
| Cb0 of (exp)
| Cb0_a of (exp)
| Cb03 of (exp)
| Cb03_a of (exp)
| Cb02 of (exp)
| Cb02_a of (exp)
| Cb023 of (exp)
| Cb023_a of (exp)
| Cb01 of (exp)
| Cb01_a of (exp)
| Cb013 of (exp)
| Cb013_a of (exp)
| Cb012 of (exp)
| Cb012_a of (exp)
| Call of (exp)
| Fmovs of (exp * exp)
| Fnegs of (exp * exp)
| Fabss of (exp * exp)
| Fsqrts of (exp * exp)
| Fsqrtd of (exp * exp)
| Fsqrtq of (exp * exp)
| Fitos of (exp * exp)
| Fstoi of (exp * exp)
| Fitod of (exp * exp)
| Fstod of (exp * exp)
| Fitoq of (exp * exp)
| Fstoq of (exp * exp)
| Fdtoi of (exp * exp)
| Fdtos of (exp * exp)
| Fqtos of (exp * exp)
| Fqtoi of (exp * exp)
| Fqtod of (exp * exp)
| Fdtoq of (exp * exp)
| Fadds of (exp * exp * exp)
| Fsubs of (exp * exp * exp)
| Fmuls of (exp * exp * exp)
| Fdivs of (exp * exp * exp)
| Faddd of (exp * exp * exp)
| Fsubd of (exp * exp * exp)
| Fmuld of (exp * exp * exp)
| Fdivd of (exp * exp * exp)
| Faddq of (exp * exp * exp)
| Fsubq of (exp * exp * exp)
| Fmulq of (exp * exp * exp)
| Fdivq of (exp * exp * exp)
| Fsmuld of (exp * exp * exp)
| Fdmulq of (exp * exp * exp)
| Fcmps of (exp * exp)
| Fcmpes of (exp * exp)
| Fcmpd of (exp * exp)
| Fcmped of (exp * exp)
| Fcmpq of (exp * exp)
| Fcmpeq of (exp * exp)
| Nop of unit
| Flush of (exp)
| Jmpl of (exp * exp)
| Rett of (exp)
| Tn of (exp)
| Te of (exp)
| Tle of (exp)
| Tl of (exp)
| Tleu of (exp)
| Tcs of (exp)
| Tneg of (exp)
| Tvs of (exp)
| Ta of (exp)
| Tne of (exp)
| Tg of (exp)
| Tge of (exp)
| Tgu of (exp)
| Tcc of (exp)
| Tpos of (exp)
| Tvc of (exp)
| Unimp of (exp)
| Sethi of (exp * exp)
| Decode_sethi of (exp * exp)
| Set of (exp * exp)



val pprint : exp ->
unit

