TOP=..
<../config/ocaml.mk
<../config/noweb.mk

all:V: lua.cmi lua.cmo
src:V: lua.ml lua.mli

depend:V: DEPEND

clean:V:
	rm -f *.cmi *.cmo *.ml *.mli

DEPEND: src `echo *.ml *.mli`
	$OCAMLDEP *.ml *.mli > $target

<DEPEND
