#!/bin/sh

awk '
/^@text / && ($2 == "(*unboxval*)" || $2 == "(*inboxval*)") {
  print "@literal \\eatline"; next 
}
/^@text / && $2 == "(*boxval" {
   line=$0
   sub(/^@text ..boxval */, "", line)
   sub(/[*][)]$/, "", line)
   printf "@literal \\hfill\\fbox{%s}\\hskip\\nwdefspace\n", line
   next
}
{ print }' $*
