# ------------------------------------------------------------------ 
# $Id$
# ------------------------------------------------------------------ 

NAME = libqc--
TOP  = ..
<      $TOP/config/config.mk
B=""

LIBA   = ${B}$NAME.a
DEPEND = ${B}DEPEND

QCMM=`if [ -x $TOP/bin/qc--.opt ]; then echo $TOP/bin/qc--.opt; else echo $TOP/bin/qc--; fi`

# ------------------------------------------------------------------ 
# (high level) virtual targets
# ------------------------------------------------------------------ 

NW   = pcmap.nw gcc-linux.nw runtime.nw
HTML = ${NW:%.nw=%.html}
INC  = ${NW:%.nw=%.inc}

all:V:     $LIBA pcmap.ld qc--runtime.h
all.opt:V: all
doc:V:     doc.ps
dvi:V:     doc.dvi
html:V:    $HTML
depend:V:  $DEPEND
install:V: $LIBA pcmap.ld qc--runtime.h
	for i in $prereq;       do install -D -m 644 $i $install_lib/$i; done
	for i in qc--runtime.h; do install -D -m 644 $i $install_inc/$i; done
install.opt:V: install

test:V: all test.exe

doc.dvi: doc.tex $INC

update:V: all
	cp $LIBA pcmap.ld $TOP/lib
	cp qc--runtime.h $TOP/include

update.opt:V: update

# ------------------------------------------------------------------ 
# cleanup
# ------------------------------------------------------------------ 

clean.opt:V:
	rm -f $B*.o $B*.a $B*.s thread.c-- cut.c--

clean:V: clean.opt

clobber:V: clean
	rm -f DEPEND $C $H *.s
	rm -f pcmap.ld *.exe
	rm -f *.aux *.log *.dvi *.toc *.inc *.ps *.html

# ------------------------------------------------------------------ 
# rules and tools
# ------------------------------------------------------------------ 

<$TOP/config/noweb.mk
<$TOP/config/latex.mk

# ------------------------------------------------------------------ 
# important file sets
# ------------------------------------------------------------------ 

C = runtime.c pcmap.c gcc-linux.c
CMM = cut.c-- thread.c--
H = qc--runtime.h pcmap.h

C = ${C:%.c=$B%.c}
CMM = ${CMM:%=$B%}
H = ${H:%.h=$B%.h}
O = ${C:%.c=%.o} ${CMM:%.c--=%.o} $config_arch.o

SCAN = $C trace.c
# <$TOP/config/depend.mk
$DEPEND:D: $SCAN mkfile $H
	gcc -MM $SCAN > $DEPEND
<$DEPEND

dep-chk:V:
	echo

# ------------------------------------------------------------------ 
# build the libraries
# ------------------------------------------------------------------ 

$LIBA:  $O
	ar cr $target $prereq

test.exe: test.o trace.o $LIBA pcmap.ld
	gcc -o $target $prereq

pcmap.ld:D: pcmap.nw
	$NOTANGLE $prereq -R$target > $target

&.o: &.s
	as -o $target $stem.s

&.s: &.c
	gcc -Wall -S $stem.c

# ------------------------------------------------------------------ 
# machine-dependent code
# ------------------------------------------------------------------ 

x86-linux.o: x86cont.s
	as -o $target $prereq

x86cont.s:D: x86cont.nw
	$NOTANGLE $prereq -R$target > $target

powerpc-darwin.o:
	cc -c -o $target -x c /dev/null

sparc-solaris.o:
	gcc -c -o $target -x c /dev/null

# ------------------------------------------------------------------ 
# extra rules for cases not covered by noweb.mk
# ------------------------------------------------------------------ 

&.h:D: &.nw
	$NOTANGLE -L $prereq -R$target > $target

qc--runtime.h:D: runtime.nw
	$NOTANGLE -L $prereq -R$target > $target

${B}cut.c--:D: runtime.nw
	$NOTANGLE -L $prereq -R$target > $target

${B}thread.c--:D: runtime.nw
	$NOTANGLE -L $prereq -R$target > $target

${B}&.s:D: ${B}&.c--
	tmp=/tmp/$stem$$
	$QCMM $config_swapopt -S -o $tmp ${B}$stem.c--
	sed '/globalsig/d;/ref_to_global_area/d' $tmp > $target
	rm -f $tmp
