TOP=..
INTERP=evaluating

<../config/noweb.mk

all:V: doc coders

doc:V: design.ps state.ps

coders:V: encode.h encode.c decode.c

design.tex: design.inc
	echo "\input{design.inc}" > $target

state.tex: state.inc
    echo "\input{state.inc}" > $target

clean:V: clean-tex
	rm -f design.tex state.tex bytecode.tex *~

clean-tex:V:
	rm -f *.blg *.log *.dvi *.inc *.toc *.aux

bytecode.sled:D: bytecode.nw
	$NOTANGLE -L -R$target $prereq > $target

decode.fetch:D: bytecode.nw
	$NOTANGLE -L -R$target $prereq > $target

decode.m:D: bytecode.nw
	$NOTANGLE -L -R$target $prereq > $target

interp.h:D: bytecode.nw
        $NOTANGLE -L -R$target $prereq > $target

encode.c encode.h: bytecode.sled
	tools -lc-cons-names -encoder encode $prereq

%.c:D: %.m bytecode.sled decode.fetch
	tools -lc-cons-names -decoder $target -matcher $stem.m \
		bytecode.sled decode.fetch

interp.o: decode.c interp.h
        gcc -c -o interp.o decode.c
