#!/bin/sh

MODE=$1

cat <<EOF 1>&2
You have attempted to build files encode.c and encode.h from a SLED
specification, but you have set MODE=$MODE.  It is possible to build
these files only when MODE=developer and when you TOOLS set to point
to an executable version of the New Jersey Machine-Code Toolkit.
Either avoid editing the bytecode definitions or install the Toolkit
and re-run using MODE=developer.
EOF
exit 1
