#!/bin/sh

MODE=$1
shift

cat <<EOF 1>&2
You have attempted to build these files:
    "$*" 
These files must be built from a SLED specification using the New
Jersey Machine-Code Toolkit, which is possible only with
MODE=developer.  You have set MODE=$MODE.  Either avoid editing the
bytecode and encoding files or install the Toolkit and re-run using mk
MODE=developer TOOLS=<tools-pathname>.
EOF
exit 1
