#!/bin/sh

MODE=$1
shift

cat <<EOF 1>&2
You have attempted to build these files:
    "$*" 
These files must be built from a SLED specification using the New
Jersey Machine-Code Toolkit, which is possible only with
MODE=developer.  You have set MODE=$MODE.  Either avoid editing the
bytecode and encoding files or install the Toolkit and re-run using mk
MODE=developer TOOLS=<tools-pathname>.

(It may be that you have received this message not because you have edited
bytecode files but because you are working directly from our CVS repository.
CVS makes it difficult to keep time stamps up to date.  You can work around
this problem by typing 'mk timestamps' in the toplevel directory as described
in the INSTALL file.)
EOF
exit 1
