# V2_5 is a list of benchmarks that can reasonably be expected to work using lua 2.5

V2_5=ackermann ary ary2 ary3 fibo hash hash2 heapsort list matrix moments nestedloop random

# need input: moments

INTERP=std
PROFILE=-p

bin:VQ: 
	(cd ../lua      && mk INTERP=$INTERP PROFILE=$PROFILE update.opt)
	### (cd ../lua-uniq && mk all.opt && copy -v oclbench.opt /usr/local/bin/oclbenchu)
