#!/bin/sh

# usage: mkjgraph interp foo.lua sizes

case $# in 
  0|1|2) echo "Usage: $0 interp bench.lua <sizes>" 1>&2; exit 1 ;;
esac

interp=$1
bench=$2
echo newgraph newcurve linetype solid pts
shift; shift
for x
do
  (/usr/bin/time -f "$x %e " $interp $bench $x > /dev/null) 2>&1
done
