INSTALL=/usr/local/lib/tiger

refresh:VQ: stdlib-x86.a tigermain-x86.o
	[ -r $INSTALL/runtime.o -a -r $INSTALL/stdlib.a ] ||
	{ echo "Bad news!  No installed tiger from which to update!"; exit 2; }

stdlib-x86.a:  $INSTALL/stdlib.a
	cp $prereq $target

tigermain-x86.o:  $INSTALL/runtime.o
	cp $prereq $target

