.TH call-test 1 "29 April 1996"
.SH NAME
call-test - Procedure calling convention exerciser
.SH SYNOPSIS
call-test [
.I options 
] file
.SH DESCRIPTION
.PP
.I call-test
is a
.I perl
script that exercises and diagnoses errors in procedure calling convention
implementations in C compilers.
.I call-test
uses
.IR tgen (1)
to generate test cases from a CCL (Calling Convention Language)
convention table.
.I call-test
uses a reference compiler (typically the native compiler on the target
machine) to determine if the compiler-under-test (CUT) properly passes
values between a C caller and callee function.
.SH OPTIONS
.IP "\-f file" 8
Exercise a single test case named 
.IR file .
If the test case does not exist, create it.
.IP \-n
Print out the actions that
.I call-test
would take, but do not actually perform them. Similar is flavor to the
.i make
\-n flag.
.IP "\-q name"
quick string
.IP "\-s name"
Start test exercising with test case named
.IR name .
This enables 
.I call-test
to pick up in the middle of a run.
.IP \-x 
.IP \-v
varargs versions
.IP \-S 
passes -s on to tgen
.IP \-V 
Print 
.I call-test 
version number.
.SH SETTINGS FILES
.I call-test
requires two files: a settings file and a convention table file. The
settings file's default name is 
.IR test.settings .
This file contains values for each of the variables that 
.I call-test
uses. These are:
.IP HOST 8
The hostname of the machine that the 
.I tgen
test program generator runs on.
.IP TARGET
The target architecture for the C compiler.
.IP REF
The command for running the reference compiler
.IP CC
The command for running the compiler-under-test. More than one
.I CC
line may be present to test more than one compiler for conformance
simultaneously.

.SH FILES
test.settings
.SH SEE ALSO
tgen(1)

