#
#

TOP     = ..

all:V:          cfg.dvi better.dvi working.dvi

<../config/noweb.mk

cfg.tex:        cfg.nw
                $NOWEAVE -delay cfg.nw > $target 
                
clean:V:
                rm -f *.dvi *.aux *.log *.toc                
                rm -f cfg.tex
