#
#

TOP     = ..

all:V:          cfg.ps better.ps working.ps newtarget.ps modules.ps

<../config/noweb.mk

cfg.tex:        cfg.nw
                $NOWEAVE -delay cfg.nw > $target 

modules.ps:     modules.txt
                a2ps -B -9 -r -f 12 -o $target modules.txt

clean:V:
                rm -f *.dvi *.aux *.log *.toc                
                rm -f cfg.tex modules.ps
