Document: qcmm
Title: Debian qcmm Manual
Author: <insert document author here>
Abstract: This manual describes what qcmm is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qcmm/qcmm.sgml.gz

Format: postscript
Files: /usr/share/doc/qcmm/qcmm.ps.gz

Format: text
Files: /usr/share/doc/qcmm/qcmm.text.gz

Format: HTML
Index: /usr/share/doc/qcmm/html/index.html
Files: /usr/share/doc/qcmm/html/*.html

  
