# ------------------------------------------------------------------ 
# mkfile for test suite
# $Id$
# ------------------------------------------------------------------ 

TOP =           ..
PATH =          $PATH:$TOP/bin
QC   =          $TOP/bin/qc--
TST  =          `echo *.tst`

<               $TOP/config/config.mk
<               $TOP/config/noweb.mk
<               $TOP/config/c.mk

# ------------------------------------------------------------------ 
# High level virtual targets. 
# all - run all .tst files
# ------------------------------------------------------------------ 

all:V:    test
test:V:   $TST

test-lua:V: testdrv.lua
	$NOTANGLE -L'$file "%F"%N$line %L%N' -Rexample.tst testdrv.nw > example.tst
	$QC testdrv.lua example.tst

clean:V:            
	rm -f *.dvi *.log *.aux *.inc *.tex *.toc

clobber:V: clean
	rm -f testqc testdrv.lua example.tst

# ------------------------------------------------------------------ 
# Rules for individual test cases
# ------------------------------------------------------------------ 

testdrv.lua:D:  testdrv.nw
	$NOTANGLE -L'$file "%F"%N$line %L%N' -R$target $prereq > $target

%.tst:V: $QC testdrv.lua
	$QC testdrv.lua $target

tiger.tst:QV:
	echo 'print("hello\n")' > /tmp/hello.tig
	if < /tmp/hello.tig ../../frontends/tiger/tigerc 1>/dev/null 2>/dev/null; then
	  rm -f /tmp/hello.tig
	  $QC testdrv.lua tiger.tst
	else
	  rm -f /tmp/hello.tig
	  echo "# Cannot execute Tiger compiler" 1>&2
	fi

################################################################

opgen: opgen.o
	$CC $CFLAGS -o $target $prereq

ops%.c--:D: opgen
	./opgen $stem > $target

%: %.c--
	$QC -v -globals -o $target $prereq

'^optest([0-9]*)$':VR: ops'\1'
	./$prereq
