
OBJ     =       `find . -name '*.obj' -print`
EPS     =       `echo $OBJ | sed 's/.obj/.eps/g'`

TGIF    =       tgif

all:V:          $EPS

%.eps:          %.obj
                $TGIF -print -eps $prereq
