# ------------------------------------------------------------------ 
# $Id$ 
# ------------------------------------------------------------------ 

NAME =      ocamlerror

# ------------------------------------------------------------------ 
# paths
# ------------------------------------------------------------------ 

TOP    =    ..
INTERP =    evaluating
DEPEND =    DEPEND

LIBDIR =    ../lib
BINDIR =    ../bin
MANDIR =    ../man

prefix =    /usr/local

# ------------------------------------------------------------------ 
# (high level) virtual targets
# ------------------------------------------------------------------ 

HTML =          `echo *.nw       | sed 's/\.nw/.html/g;'`
INC  =          `echo *.nw       | sed 's/\.nw/.inc/g;'`

all:V:          ocamlerror      man
all.opt:V:      ocamlerror.opt  man
update:V:       
update.opt:V:   

dvi:V:          $INC
html:V:         $HTML

man:V:          ocamlerror.1

test:VQ:
                echo "nothing to be done"

depend:V:       $DEPEND

clean:V:    
                rm -f *.cmo *.cmi *.cmx *.o
                rm -f *.output
                
clobber:V:      clean
                rm -rf *.ml *.mll *.mli DEPEND 
                rm -rf ocamlerror ocamlerror.opt
                rm -rf ocamlerror.pod ocamlerror.1
                rm -rf *.aux *.log *.dvi *.tex *.inc *.toc

install:V:      all.opt
                install -s ocamlerror.opt $prefix/bin/ocamlerror
                install    ocamlerror.1   $prefix/man/man1  


# ------------------------------------------------------------------ 
# rules and tools for OCaml
# ------------------------------------------------------------------ 

<../config/ocaml.mk
<../config/noweb.mk

# compiler flags used by the rules just included

OCAMLC_FLAGS =  -g -I $LIBDIR
OCAMLO_FLAGS =     -I $LIBDIR

# ------------------------------------------------------------------ 
# important file sets
# ------------------------------------------------------------------ 

ML  =           ocamlscan.ml    \
                ocamlerror.ml   \

MLI =           


SCAN =          $ML $MLI

CMO =           `echo $ML       | sed 's/\.ml/.cmo/g'`
CMX =           `echo $ML       | sed 's/\.ml/.cmx/g'`
OBJ =           `echo $ML       | sed 's/\.ml/.o/g'`

# ------------------------------------------------------------------ 
# building binaries
# ------------------------------------------------------------------ 

CMOLIBS =       str.cma  cllib.cma
CMXLIBS =       str.cmxa cllib.cmxa

ocamlerror:     ocamlscan.cmo ocamlerror.cmo 
		$OCAMLC $OCAMLC_FLAGS -custom -o $target $CMOLIBS $prereq
                

ocamlerror.opt: ocamlscan.cmx ocamlerror.cmx 
		$OCAMLO $OCAMLO_FLAGS         -o $target $CMXLIBS $prereq

# ------------------------------------------------------------------ 
# extra rules for cases not covered by noweb.mk
# ------------------------------------------------------------------ 

ocamlscan.mll:  ocamlerror.nw
                $NOTANGLE -R$target $prereq > $target

ocamlerror.pod: ocamlerror.nw
                $NOTANGLE -R$target $prereq > $target

# ------------------------------------------------------------------ 
# rules to export source code into a world without noweb
# ------------------------------------------------------------------ 

untangle:V:     ocamlerror.pod ocamlerror.1
                nountangle -ml -Rocamlerror.ml ocamlerror.nw > ocamlerror.ml
                nountangle -ml -Rocamlscan.mll ocamlerror.nw > ocamlscan.mll
                nountangle -ml -Rsrcmap.ml  ../cllib/srcmap.nw > srcmap.ml
                nountangle -ml -Rsrcmap.mli ../cllib/srcmap.nw > srcmap.mli

# ------------------------------------------------------------------ 
# recalculate dependencies
# make sure that generators are run first
# ------------------------------------------------------------------ 

$DEPEND: 	$SCAN
		$OCAMLDEP $SCAN > $DEPEND

# ------------------------------------------------------------------ 
# include dependencies
# ------------------------------------------------------------------ 

<$DEPEND

