#
# $Id$
#

=head1 NAME

qcc - quick c--

=head1 SYNOPSIS

B<hello -version>

B<hello -help>


=head1 DESCRIPTION

B<qcc> writes I<msg> to stdout or I<hello world> when the B<-s>
option is unused.

=head1 OPTIONS

=over

=item B<-version>

Report the version of B<qcc> to stdout.

=item B<-help>

Print short usage to stderr.

=back

=head1 AUTHOR

Christian Lindig <lindig@gaertner.de>, http://www.gaertner.de/~lindig

