TOP       = ../..

HEADERS    = qc--interp.h \
             qc--runtime.h

all:V:      $HEADERS
all.opt:V:  all

# ------------------------------------------------------------------
# rules and tools 
# ------------------------------------------------------------------

<$TOP/config/noweb.mk

'(([^/]*/)*)(.*)\.h$':RD:       '\1\3.nw'
        $NOTANGLE -L"$LINE" -R$stem3.h $prereq > $target

NOTANGLEOPTS = -L
